module.exports = {
  Admin: require('./Admin'),
  Guest: require('./Guest'),
  Event: require('./Event'),
  EventImage: require('./EventImage'),
  EventChoice: require('./EventChoice'),
  Message: require('./Message'),
  Course: require('./Course'),
  CourseOption: require('./CourseOption'),
  MenuChoice: require('./MenuChoice'),
  CourseOptionImage: require('./CourseOptionImage'),
  Gift: require('./Gift'),
  GiftImage: require('./GiftImage'),
  GiftChoice: require('./GiftChoice'),
  Config: require('./Config'),
};
