module.exports = {
  Admin: require('./Admin'),
  LocalizedString: require('./LocalizedString'),
  Guest: require('./Guest'),
  Event: require('./Event'),
  EventImage: require('./EventImage'),
  EventChoice: require('./EventChoice'),
  Message: require('./Message'),
  Course: require('./Course'),
  CourseOption: require('./CourseOption'),
  CourseOptionImage: require('./CourseOptionImage'),
  MenuChoice: require('./MenuChoice'),
  Gift: require('./Gift'),
  GiftImage: require('./GiftImage'),
  GiftChoice: require('./GiftChoice'),
  Config: require('./Config'),
  ChefProfile: require('./ChefProfile'),
  ChefProfileImage: require('./ChefProfileImage'),
  DayMenu: require('./DayMenu'),
  DayMenuImage: require('./DayMenuImage'),
  Table: require('./Table'),
  TableAssignment: require('./TableAssignment'),
};
